name: Terraform Format Check

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
       - name: Set up Terraform
       run: sudo apt-get update && sudo apt-get install -y unzip


      - name: Run terraform fmt check
        run: terraform fmt -check
        id: terraform-fmt-check

      - name: Set output if Terraform formatting check fails
        run: echo "terraform_fmt_failed=true" >> $GITHUB_ENV
        if: failure()

      - name: Fail the job if Terraform formatting failed
        run: |
          if [ "$terraform_fmt_failed" == "true" ]; then
            echo "Terraform formatting failed"
            exit 1
          fi
          - name: Terraform Plan
             run: terraform plan -input=false

  # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
        
